require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ArtistHypesController do

  # This should return the minimal set of attributes required to create a valid
  # ArtistHype. As you add validations to ArtistHype, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all artist_hypes as @artist_hypes" do
      artist_hype = ArtistHype.create! valid_attributes
      get :index
      assigns(:artist_hypes).should eq([artist_hype])
    end
  end

  describe "GET show" do
    it "assigns the requested artist_hype as @artist_hype" do
      artist_hype = ArtistHype.create! valid_attributes
      get :show, :id => artist_hype.id.to_s
      assigns(:artist_hype).should eq(artist_hype)
    end
  end

  describe "GET new" do
    it "assigns a new artist_hype as @artist_hype" do
      get :new
      assigns(:artist_hype).should be_a_new(ArtistHype)
    end
  end

  describe "GET edit" do
    it "assigns the requested artist_hype as @artist_hype" do
      artist_hype = ArtistHype.create! valid_attributes
      get :edit, :id => artist_hype.id.to_s
      assigns(:artist_hype).should eq(artist_hype)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ArtistHype" do
        expect {
          post :create, :artist_hype => valid_attributes
        }.to change(ArtistHype, :count).by(1)
      end

      it "assigns a newly created artist_hype as @artist_hype" do
        post :create, :artist_hype => valid_attributes
        assigns(:artist_hype).should be_a(ArtistHype)
        assigns(:artist_hype).should be_persisted
      end

      it "redirects to the created artist_hype" do
        post :create, :artist_hype => valid_attributes
        response.should redirect_to(ArtistHype.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved artist_hype as @artist_hype" do
        # Trigger the behavior that occurs when invalid params are submitted
        ArtistHype.any_instance.stub(:save).and_return(false)
        post :create, :artist_hype => {}
        assigns(:artist_hype).should be_a_new(ArtistHype)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ArtistHype.any_instance.stub(:save).and_return(false)
        post :create, :artist_hype => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested artist_hype" do
        artist_hype = ArtistHype.create! valid_attributes
        # Assuming there are no other artist_hypes in the database, this
        # specifies that the ArtistHype created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ArtistHype.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => artist_hype.id, :artist_hype => {'these' => 'params'}
      end

      it "assigns the requested artist_hype as @artist_hype" do
        artist_hype = ArtistHype.create! valid_attributes
        put :update, :id => artist_hype.id, :artist_hype => valid_attributes
        assigns(:artist_hype).should eq(artist_hype)
      end

      it "redirects to the artist_hype" do
        artist_hype = ArtistHype.create! valid_attributes
        put :update, :id => artist_hype.id, :artist_hype => valid_attributes
        response.should redirect_to(artist_hype)
      end
    end

    describe "with invalid params" do
      it "assigns the artist_hype as @artist_hype" do
        artist_hype = ArtistHype.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ArtistHype.any_instance.stub(:save).and_return(false)
        put :update, :id => artist_hype.id.to_s, :artist_hype => {}
        assigns(:artist_hype).should eq(artist_hype)
      end

      it "re-renders the 'edit' template" do
        artist_hype = ArtistHype.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ArtistHype.any_instance.stub(:save).and_return(false)
        put :update, :id => artist_hype.id.to_s, :artist_hype => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested artist_hype" do
      artist_hype = ArtistHype.create! valid_attributes
      expect {
        delete :destroy, :id => artist_hype.id.to_s
      }.to change(ArtistHype, :count).by(-1)
    end

    it "redirects to the artist_hypes list" do
      artist_hype = ArtistHype.create! valid_attributes
      delete :destroy, :id => artist_hype.id.to_s
      response.should redirect_to(artist_hypes_url)
    end
  end

end
