require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe FeaturedUsersController do

  # This should return the minimal set of attributes required to create a valid
  # FeaturedUser. As you add validations to FeaturedUser, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all featured_users as @featured_users" do
      featured_user = FeaturedUser.create! valid_attributes
      get :index
      assigns(:featured_users).should eq([featured_user])
    end
  end

  describe "GET show" do
    it "assigns the requested featured_user as @featured_user" do
      featured_user = FeaturedUser.create! valid_attributes
      get :show, :id => featured_user.id.to_s
      assigns(:featured_user).should eq(featured_user)
    end
  end

  describe "GET new" do
    it "assigns a new featured_user as @featured_user" do
      get :new
      assigns(:featured_user).should be_a_new(FeaturedUser)
    end
  end

  describe "GET edit" do
    it "assigns the requested featured_user as @featured_user" do
      featured_user = FeaturedUser.create! valid_attributes
      get :edit, :id => featured_user.id.to_s
      assigns(:featured_user).should eq(featured_user)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new FeaturedUser" do
        expect {
          post :create, :featured_user => valid_attributes
        }.to change(FeaturedUser, :count).by(1)
      end

      it "assigns a newly created featured_user as @featured_user" do
        post :create, :featured_user => valid_attributes
        assigns(:featured_user).should be_a(FeaturedUser)
        assigns(:featured_user).should be_persisted
      end

      it "redirects to the created featured_user" do
        post :create, :featured_user => valid_attributes
        response.should redirect_to(FeaturedUser.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved featured_user as @featured_user" do
        # Trigger the behavior that occurs when invalid params are submitted
        FeaturedUser.any_instance.stub(:save).and_return(false)
        post :create, :featured_user => {}
        assigns(:featured_user).should be_a_new(FeaturedUser)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        FeaturedUser.any_instance.stub(:save).and_return(false)
        post :create, :featured_user => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested featured_user" do
        featured_user = FeaturedUser.create! valid_attributes
        # Assuming there are no other featured_users in the database, this
        # specifies that the FeaturedUser created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        FeaturedUser.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => featured_user.id, :featured_user => {'these' => 'params'}
      end

      it "assigns the requested featured_user as @featured_user" do
        featured_user = FeaturedUser.create! valid_attributes
        put :update, :id => featured_user.id, :featured_user => valid_attributes
        assigns(:featured_user).should eq(featured_user)
      end

      it "redirects to the featured_user" do
        featured_user = FeaturedUser.create! valid_attributes
        put :update, :id => featured_user.id, :featured_user => valid_attributes
        response.should redirect_to(featured_user)
      end
    end

    describe "with invalid params" do
      it "assigns the featured_user as @featured_user" do
        featured_user = FeaturedUser.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        FeaturedUser.any_instance.stub(:save).and_return(false)
        put :update, :id => featured_user.id.to_s, :featured_user => {}
        assigns(:featured_user).should eq(featured_user)
      end

      it "re-renders the 'edit' template" do
        featured_user = FeaturedUser.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        FeaturedUser.any_instance.stub(:save).and_return(false)
        put :update, :id => featured_user.id.to_s, :featured_user => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested featured_user" do
      featured_user = FeaturedUser.create! valid_attributes
      expect {
        delete :destroy, :id => featured_user.id.to_s
      }.to change(FeaturedUser, :count).by(-1)
    end

    it "redirects to the featured_users list" do
      featured_user = FeaturedUser.create! valid_attributes
      delete :destroy, :id => featured_user.id.to_s
      response.should redirect_to(featured_users_url)
    end
  end

end
