require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe HypesController do

  # This should return the minimal set of attributes required to create a valid
  # Hype. As you add validations to Hype, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all hypes as @hypes" do
      hype = Hype.create! valid_attributes
      get :index
      assigns(:hypes).should eq([hype])
    end
  end

  describe "GET show" do
    it "assigns the requested hype as @hype" do
      hype = Hype.create! valid_attributes
      get :show, :id => hype.id.to_s
      assigns(:hype).should eq(hype)
    end
  end

  describe "GET new" do
    it "assigns a new hype as @hype" do
      get :new
      assigns(:hype).should be_a_new(Hype)
    end
  end

  describe "GET edit" do
    it "assigns the requested hype as @hype" do
      hype = Hype.create! valid_attributes
      get :edit, :id => hype.id.to_s
      assigns(:hype).should eq(hype)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Hype" do
        expect {
          post :create, :hype => valid_attributes
        }.to change(Hype, :count).by(1)
      end

      it "assigns a newly created hype as @hype" do
        post :create, :hype => valid_attributes
        assigns(:hype).should be_a(Hype)
        assigns(:hype).should be_persisted
      end

      it "redirects to the created hype" do
        post :create, :hype => valid_attributes
        response.should redirect_to(Hype.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved hype as @hype" do
        # Trigger the behavior that occurs when invalid params are submitted
        Hype.any_instance.stub(:save).and_return(false)
        post :create, :hype => {}
        assigns(:hype).should be_a_new(Hype)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Hype.any_instance.stub(:save).and_return(false)
        post :create, :hype => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested hype" do
        hype = Hype.create! valid_attributes
        # Assuming there are no other hypes in the database, this
        # specifies that the Hype created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Hype.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => hype.id, :hype => {'these' => 'params'}
      end

      it "assigns the requested hype as @hype" do
        hype = Hype.create! valid_attributes
        put :update, :id => hype.id, :hype => valid_attributes
        assigns(:hype).should eq(hype)
      end

      it "redirects to the hype" do
        hype = Hype.create! valid_attributes
        put :update, :id => hype.id, :hype => valid_attributes
        response.should redirect_to(hype)
      end
    end

    describe "with invalid params" do
      it "assigns the hype as @hype" do
        hype = Hype.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Hype.any_instance.stub(:save).and_return(false)
        put :update, :id => hype.id.to_s, :hype => {}
        assigns(:hype).should eq(hype)
      end

      it "re-renders the 'edit' template" do
        hype = Hype.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Hype.any_instance.stub(:save).and_return(false)
        put :update, :id => hype.id.to_s, :hype => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested hype" do
      hype = Hype.create! valid_attributes
      expect {
        delete :destroy, :id => hype.id.to_s
      }.to change(Hype, :count).by(-1)
    end

    it "redirects to the hypes list" do
      hype = Hype.create! valid_attributes
      delete :destroy, :id => hype.id.to_s
      response.should redirect_to(hypes_url)
    end
  end

end
